name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libgtk-3-dev libsoup2.4 openssl
    - name: Build
      run: |     
        cd src-tauri/
        cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
